# Generated by Django 4.2 on 2026-06-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('tool_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('degraded_count', models.IntegerField(default=0)),
                ('session_start_time', models.FloatField(default=0.0)),
                ('total_tool_duration_ms', models.FloatField(default=0.0)),
                ('total_estimated_input_tokens', models.BigIntegerField(default=0)),
                ('total_estimated_output_tokens', models.BigIntegerField(default=0)),
                ('last_tool_end_perf', models.FloatField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('session_trace_id', models.CharField(blank=True, default='', max_length=128)),
                ('create_op_count', models.IntegerField(default=0)),
                ('update_delete_op_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'mcp_session_stats',
            },
        ),
        migrations.CreateModel(
            name='SessionToolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('tool_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mcp_session_tool_event',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SSEMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField()),
                ('enqueued_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mcp_sse_message',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SSESession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('credentials', models.JSONField(default=dict)),
                ('session_trace_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mcp_sse_session',
            },
        ),
    ]
