# Generated by Django 4.2 on 2026-05-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OAuthClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=64, unique=True)),
                ("redirect_uris", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "oauth_client",
            },
        ),
        migrations.CreateModel(
            name="OAuthCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=128, unique=True)),
                ("client_id", models.CharField(max_length=64)),
                ("redirect_uri", models.TextField()),
                ("code_challenge", models.CharField(max_length=256)),
                ("credentials", models.JSONField()),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "oauth_code",
            },
        ),
        migrations.CreateModel(
            name="OAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=128, unique=True)),
                ("credentials", models.JSONField()),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "oauth_token",
            },
        ),
    ]
