# Generated by Django 4.2 on 2026-06-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_remove_oauthtoken_expires_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIClient',
        ),
        migrations.AlterModelOptions(
            name='oauthtoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'OAuth Token', 'verbose_name_plural': 'OAuth Tokens'},
        ),
        migrations.AlterField(
            model_name='oauthclient',
            name='client_id',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
