# Generated by Django 4.2 on 2026-06-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_remove_oauthtoken_expires_at'),
    ]

    operations = [
        # The ai_client table was already dropped from the database in 0007
        # (DROP TABLE IF EXISTS, with state_operations=[]), which left AIClient
        # in the migration STATE only. A plain DeleteModel here would emit a
        # second DROP TABLE and fail with "no such table: ai_client" on any
        # database that already ran 0007 (e.g. Railway). Make this a state-only
        # delete so the model leaves the migration graph without a second DROP.
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.DeleteModel(name='AIClient')],
            database_operations=[],
        ),
        migrations.AlterModelOptions(
            name='oauthtoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'OAuth Token', 'verbose_name_plural': 'OAuth Tokens'},
        ),
        migrations.AlterField(
            model_name='oauthclient',
            name='client_id',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
