# Generated by Django 4.2 on 2026-06-15 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_strip_publisher_id_from_credentials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OAuthCode',
        ),
    ]
