# Generated by Django 4.2 on 2026-06-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_delete_oauthcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthAuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=128, unique=True)),
                ('client_id', models.CharField(blank=True, default='', max_length=64)),
                ('redirect_uri', models.CharField(blank=True, default='', max_length=512)),
                ('code_challenge', models.CharField(blank=True, default='', max_length=128)),
                ('credentials', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OAuth Authorization Code',
                'verbose_name_plural': 'OAuth Authorization Codes',
                'db_table': 'oauth_authorization_code',
                'ordering': ['-created_at'],
            },
        ),
    ]
